Ajust workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,12 +21,22 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Start ServeRest (local)
+      - name: Start Serverest using Docker
+        run: docker run -d --name serverest -p 3000:3000 serverest/serverest:latest
+  
+      - name: Wait for Serverest to be ready
         run: |
-          docker pull paulogoncalvesbh/serverest:latest
-          docker run -d --name serverest -p 3000:3000 paulogoncalvesbh/serverest
-          sleep 30  # Espera o servidor iniciar
-
+          for i in {1..30}; do
+            if curl --silent http://localhost:3000/health | grep "OK"; then
+              echo "Server is ready!"
+              exit 0
+            fi
+            echo "Waiting for server to be ready..."
+            sleep 5
+          done
+          echo "Server failed to start in time."
+          exit 1
+          
       - name: Run Cypress Tests
         uses: cypress-io/github-action@v6
         with:
